# Generated by Django 5.2.10 on 2026-02-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, help_text='PDF/report/flyer/poster file', null=True, upload_to='items/files/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Main photo for products', null=True, upload_to='items/images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, default='UGX', max_length=10),
        ),
    ]
